// Game Results
var TEXT_GAMEOVER = "VICTORY!";
var TEXT_LOSE = "DEFEAT! PLAYER %s HAS WON";
var TEXT_SCORE = "SCORE";
var TEXT_RESTART = "PLAY AGAIN";
var TEXT_ARE_SURE = "CONFIRM ACTION";
var TEXT_WINNER = "CHAMPION!";
var TEXT_PLAYER_WON = "%s IS THE WINNER!";
var TEXT_SUMMARY = "GAME SUMMARY";
var TEXT_PTS_TO_WINNER = "%s POINTS AWARDED";

// Player Setup
var TEXT_SELECT_PLAYERS = "SELECT PLAYER COUNT";
var TEXT_SELECT_COLOR = "CHOOSE YOUR COLOR";
var TEXT_PLAYER_1 = "PLAYER 1";
var TEXT_PLAYER_2 = "PLAYER 2";
var TEXT_PLAYER_3 = "PLAYER 3";
var TEXT_PLAYER_4 = "PLAYER 4";

// Tutorial
var TEXT_WELCOME = "WELCOME TO FOUR COLORS";
var TEXT_TUTORIAL1 = "MATCH CARDS BY COLOR OR NUMBER TO ELIMINATE THEM FIRST!\n\nWINNING SCORE = SUM OF OPPONENTS' CARDS. FIRST TO %s PTS WINS!\n\nNUMBER CARDS: FACE VALUE";
var TEXT_TUTORIAL2 = "SPECIAL ACTION CARDS:\n\nDRAW TWO: +2 CARDS FOR NEXT PLAYER (SKIPS TURN)\nVALUE: +%s PTS";
var TEXT_TUTORIAL3 = "SKIP: BLOCKS NEXT PLAYER\nVALUE: +%s PTS";
var TEXT_TUTORIAL4 = "REVERSE: CHANGES PLAY DIRECTION\nVALUE: +%s PTS";
var TEXT_TUTORIAL5 = "WILD: PLAY ANY TIME + CHANGE COLOR\nVALUE: +%s PTS";
var TEXT_TUTORIAL6 = "WILD DRAW FOUR: CHANGE COLOR + NEXT PLAYER DRAWS 4\n(RESTRICTED USE: NO PLAYABLE CARDS IN HAND)\nVALUE: +%s PTS";
var TEXT_TUTORIAL7 = "REMEMBER: PRESS 'LAST CARD' WHEN DOWN TO 1 CARD OR DRAW %s PENALTY CARDS!";

// Alerts
var TEXT_ALERT_1 = "MUST PRESS 'LAST CARD' WITH 1 CARD REMAINING. PENALTY: +%s CARDS";
var TEXT_ALERT_2 = "%s PENALIZED +%s CARDS FOR MISSING 'LAST CARD' CALL";

// Multiplayer
var TEXT_WAIT_OPPONENT = "WAITING FOR OPPONENT...";
var TEXT_OPPONENT_LEFT = "OPPONENT DISCONNECTED";
var TEXT_PLAYER_DISCONNECTED = "YOU DISCONNECTED";
var TEXT_REMATCH = "REMATCH?";
var TEXT_QUIT_FROM_GAME = "%s HAS LEFT THE GAME";
var TEXT_THINKING = "OPPONENT'S TURN";

// Lobby System
var TEXT_SYS_CHOOSENICK = "ENTER NICKNAME";
var TEXT_SYS_UPDATE = "UPDATE";
var TEXT_SYS_MATCH_LIST = "AVAILABLE GAMES";
var TEXT_SYS_QUICKMATCH = "QUICK PLAY";
var TEXT_SYS_CREATEMATCH = "CREATE GAME";
var TEXT_SYS_BACK = "BACK";
var TEXT_SYS_OK = "CONFIRM";
var TEXT_SYS_CREATE = "CREATE";
var TEXT_SYS_CLOSE = "CLOSE";
var TEXT_SYS_LOADING = "LOADING...";
var TEXT_SYS_NAMEROOM = "ROOM NAME";
var TEXT_SYS_CREATEROOM = "CREATE ROOM";
var TEXT_SYS_PASSWORD = "PASSWORD";
var TEXT_SYS_INFOPASS = "Leave blank for public room";
var TEXT_SYS_TYPEROOMPASS = "ENTER ROOM PASSWORD";
var TEXT_WRONG_PASSWORD = "INCORRECT PASSWORD";
var TEXT_NETWORK_CONNECTING = "CONNECTING...";
var TEXT_ROOM_IS_FULL = "ROOM FULL";
var TEXT_ROOM_IS_EXPIRED = "ROOM EXPIRED";
var TEXT_MATCH_FOUND = "GAME FOUND!";
var TEXT_FIND_OPPONENT = "SEARCHING FOR PLAYERS...";
var TEXT_CONNECT_TO_LOBBY = "CONNECTING TO LOBBY...";
var TEXT_ROOM_DOESNT_EXIST = "ROOM NOT FOUND";
var TEXT_WAITING_FOR_OPPONENT_IN_ROOM = "WAITING IN ROOM: ";
var TEXT_WAITING_FOR_PLAYERS_IN_ROOM = "WAITING FOR PLAYERS: ";
var TEXT_PLAY_NOW = "START GAME";
var TEXT_WAITING_ROOM_MESSAGE = "MAX PLAYERS: %d";
var TEXT_SYS_MAXPLAYERS = "PLAYER LIMIT";
var TEXT_SYS_CHOOSEMAXNUMPLAYERS = "SET MAXIMUM PLAYERS";
var TEXT_NO_CONNECTION = "OFFLINE MODE\n(Connect for multiplayer)";
var TEXT_SYS_ADD_BOT = "ADD AI";
var TEXT_SYS_REMOVE_BOT = "REMOVE AI";
var TEXT_SOMETHING_WENT_WRONG = "NETWORK ERROR";

// Meta
var TEXT_PRELOADER_CONTINUE = "BEGIN";
var TEXT_DEVELOPED = "CREDITS";